-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "Parkovki"."Bagration"
(
    id integer NOT NULL,
    "UIN" integer NOT NULL,
    "Status" boolean NOT NULL,
    "Date" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Bagration_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Parkovki"."Benefits"
(
    id integer NOT NULL,
    "District" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    "Number" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    "Validity Period" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Benefits_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Parkovki"."Fine"
(
    id integer NOT NULL,
    "UIN" integer NOT NULL,
    "Date-Time" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    "Status" boolean[] NOT NULL,
    "Sum" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Fine_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Parkovki"."MCD"
(
    id integer NOT NULL,
    "Status" boolean NOT NULL,
    "UIN" integer NOT NULL,
    "Date" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "MCD_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Parkovki"."Parkovki"
(
    id integer NOT NULL,
    "Zone Number" integer NOT NULL,
    "Number of seats" integer NOT NULL,
    "Cost" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    "Invalide" boolean NOT NULL,
    CONSTRAINT "Parkovki_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Parkovki"."TollRoads"
(
    id integer NOT NULL,
    "idMCD" integer NOT NULL,
    "idBagration" integer NOT NULL,
    "id_MCD" integer,
    "id_Bagration" integer,
    CONSTRAINT "TollRoads_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Parkovki"."TroikaCard"
(
    id integer NOT NULL,
    "Balance" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    "Number" integer NOT NULL,
    "Validity Period" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "TroikaCard_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Parkovki"."User"
(
    "id user" integer NOT NULL,
    "Name" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    "Phone Number" character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    "Car " character varying(255)[] COLLATE pg_catalog."default",
    "Email" character varying(255)[] COLLATE pg_catalog."default",
    "STS" integer,
    id_parkovki integer,
    id_benefits integer,
    id_fine integer,
    id_troika integer,
    id_tollroads integer,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id user")
);

CREATE TABLE IF NOT EXISTS "Parkovki"."Benefits_Parkovki"
(
    "Benefits_id" integer NOT NULL,
    "Parkovki_id" integer NOT NULL
);

ALTER TABLE IF EXISTS "Parkovki"."TollRoads"
    ADD CONSTRAINT "MCD_fkey" FOREIGN KEY ("id_MCD")
    REFERENCES "Parkovki"."MCD" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."TollRoads"
    ADD CONSTRAINT "Bagration_fkey" FOREIGN KEY ("id_Bagration")
    REFERENCES "Parkovki"."Bagration" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."User"
    ADD CONSTRAINT parkovki_fkey FOREIGN KEY (id_parkovki)
    REFERENCES "Parkovki"."Parkovki" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."User"
    ADD CONSTRAINT fine_fkey FOREIGN KEY (id_fine)
    REFERENCES "Parkovki"."Fine" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."User"
    ADD CONSTRAINT troika_fkey FOREIGN KEY (id_troika)
    REFERENCES "Parkovki"."TroikaCard" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."User"
    ADD CONSTRAINT benefits_fkey FOREIGN KEY (id_benefits)
    REFERENCES "Parkovki"."Benefits" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."User"
    ADD CONSTRAINT tollroads_fkey FOREIGN KEY (id_tollroads)
    REFERENCES "Parkovki"."TollRoads" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."Benefits_Parkovki"
    ADD FOREIGN KEY ("Benefits_id")
    REFERENCES "Parkovki"."Benefits" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "Parkovki"."Benefits_Parkovki"
    ADD FOREIGN KEY ("Parkovki_id")
    REFERENCES "Parkovki"."Parkovki" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;